name: shortvideoapp
description: A short video app Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.4.0
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^9.0.0
  video_player: ^2.10.0
  intl: ^0.20.2
  image_picker: ^1.0.7
  video_thumbnail: ^0.5.6
  dio: ^5.8.0+1
  video_compress: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true